<?php

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateCustomerInformationFiles extends Migration
{

    public $tableName = 'customer_information_files';
    public $connect   = 'mysql_zenon';

    public function up() {
        Schema::connection($this->connect)->create($this->tableName, function(Blueprint $table) {
            $table->increments("id");
            $table->integer("record_code");
            $table->integer("prefecture_code");
            $table->integer("organization_code");
            $table->integer("store_number")->index();
            $table->integer("customer_number");
            $table->integer("subject_code");
            $table->integer("cir_state_001");
            $table->integer("cir_state_002");
            $table->integer("cir_state_003");
            $table->integer("cir_state_004");
            $table->integer("cir_state_005");
            $table->integer("cir_state_006");
            $table->integer("cir_state_007");
            $table->integer("cir_state_008");
            $table->integer("cir_state_009");
            $table->integer("cir_state_010");
            $table->integer("cir_state_011");
            $table->integer("cir_state_012");
            $table->integer("cir_state_013");
            $table->integer("cir_state_014");
            $table->integer("cir_state_015");
            $table->integer("cir_state_016");
            $table->integer("cir_state_017");
            $table->integer("cir_state_018");
            $table->integer("cir_state_019");
            $table->integer("cir_state_020");
            $table->integer("cir_state_021");
            $table->integer("cir_state_022");
            $table->integer("cir_state_023");
            $table->integer("cir_state_024");
            $table->integer("cir_state_025");
            $table->integer("cir_state_026");
            $table->integer("cir_state_027");
            $table->integer("cir_state_028");
            $table->integer("cir_state_029");
            $table->integer("cir_state_030");
            $table->integer("cir_state_031");
            $table->integer("cir_state_032");
            $table->integer("cir_state_033");
            $table->integer("cir_state_034");
            $table->integer("cir_state_035");
            $table->integer("cir_state_036");
            $table->integer("cir_state_037");
            $table->integer("cir_state_038");
            $table->integer("cir_state_039");
            $table->integer("cir_state_040");
            $table->integer("cir_number")->index();
            $table->integer("cir_created_on")->nullable();
            $table->integer("total_account_count");
            $table->integer("attention_code_1_001");
            $table->integer("attention_code_1_002");
            $table->integer("attention_code_1_003");
            $table->integer("attention_code_1_004");
            $table->integer("attention_code_1_005");
            $table->integer("attention_code_1_006");
            $table->integer("attention_code_1_007");
            $table->integer("attention_code_1_008");
            $table->integer("attention_code_3_001");
            $table->integer("attention_code_3_002");
            $table->integer("attention_code_3_003");
            $table->integer("attention_code_3_004");
            $table->integer("attention_code_3_005");
            $table->integer("attention_code_3_006");
            $table->integer("attention_code_3_007");
            $table->integer("attention_code_3_008");
            $table->char("name_initial", 1);
            $table->char("kana_name", 44);
            $table->char("kanji_name", 44);
            $table->char("address_state", 1);
            $table->double("address_code");
            $table->char("zip_code", 7);
            $table->char("kanji_address", 100);
            $table->char("auxiliary_address", 30);
            $table->char("trade_name", 40);
            $table->char("delegate_name", 40);
            $table->integer("gender");
            $table->date("birth_on")->nullable();
            $table->char("home_phone_number", 14);
            $table->integer("qualification_code")->index();
            $table->date("qualification_got_on")->nullable();
            $table->integer("personality_code")->index();
            $table->integer("area_code")->index();
            $table->integer("interest_rate_application_state");
            $table->integer("industry_code")->index();
            $table->integer("staff_code");
            $table->integer("jifuri_state_001");
            $table->integer("jifuri_state_002");
            $table->integer("jifuri_state_003");
            $table->integer("jifuri_state_004");
            $table->integer("jifuri_state_005");
            $table->integer("jifuri_state_006");
            $table->integer("jifuri_state_007");
            $table->integer("jifuri_state_008");
            $table->integer("jifuri_state_009");
            $table->integer("jifuri_state_010");
            $table->integer("jifuri_state_011");
            $table->integer("jifuri_state_012");
            $table->integer("jifuri_state_013");
            $table->integer("jifuri_state_014");
            $table->integer("jifuri_state_015");
            $table->integer("jifuri_state_016");
            $table->integer("jifuri_state_017");
            $table->integer("jifuri_state_018");
            $table->integer("jifuri_state_019");
            $table->integer("jifuri_state_020");
            $table->integer("jifuri_state_021");
            $table->integer("jifuri_state_022");
            $table->integer("jifuri_state_023");
            $table->integer("jifuri_state_024");
            $table->integer("jifuri_state_025");
            $table->integer("jifuri_state_026");
            $table->integer("jifuri_state_027");
            $table->integer("jifuri_state_028");
            $table->integer("jifuri_state_029");
            $table->integer("jifuri_state_030");
            $table->integer("jifuri_state_031");
            $table->integer("jifuri_state_032");
            $table->integer("lir_number")->index();
            $table->integer("small_store_number")->index();
            $table->integer("tax_not_application_state");
            $table->date("divided_taxation_on")->nullable();
            $table->char("spare_1", 50);
            $table->integer("name_correction_level");
            $table->integer("name_correction_customer_number")->index();
            $table->integer("loan_target_state");
            $table->integer("management_aggravation_state");
            $table->integer("valuation_target_state");
            $table->integer("loan_extract_001");
            $table->integer("loan_extract_002");
            $table->integer("loan_extract_003");
            $table->integer("loan_extract_004");
            $table->integer("loan_extract_005");
            $table->integer("loan_extract_006");
            $table->integer("loan_extract_007");
            $table->integer("loan_extract_008");
            $table->integer("loan_extract_009");
            $table->integer("loan_extract_010");
            $table->integer("loan_extract_011");
            $table->integer("loan_extract_012");
            $table->integer("loan_extract_013");
            $table->integer("loan_extract_014");
            $table->integer("loan_extract_015");
            $table->integer("loan_extract_016");
            $table->integer("loan_extract_017");
            $table->integer("loan_extract_018");
            $table->integer("joint_deposit_state");
            $table->integer("my_number_personality_state");
            $table->double("corporation_number");
            $table->char("foreign_account_state", 1);
            $table->integer("foreign_account_country_code");
            $table->char("spare_2", 19);
            $table->integer("maruyu_all_amount");
            $table->integer("maruzai_all_count");
            $table->integer("maruyu_store_amount");
            $table->integer("maruyu_usage_amount");
            $table->integer("maruzai_store_amount");
            $table->integer("maruzai_usage_amount");
            $table->date("new_maruyu_managed_on")->nullable();
            $table->date("maruyu_regard_disuse_on")->nullable();
            $table->date("maruyu_regard_disuse_started_on")->nullable();
            $table->integer("maruyu_usage_actual_balance");
            $table->double("loan_limit_amount");
            $table->char("previous_prefecture_code", 1)->nullable();
            $table->integer("letter_destination_state");
            $table->integer("105_notification_state");
            $table->integer("134_notification_state");
            $table->integer("138_notification_state");
            $table->integer("147_notification_state");
            $table->integer("169_notification_state");
            $table->integer("223_notification_state");
            $table->integer("245_notification_state");
            $table->integer("315_notification_state");
            $table->integer("324_notification_state");
            $table->integer("325_notification_state");
            $table->integer("334_notification_state");
            $table->integer("335_notification_state");
            $table->integer("339_notification_state");
            $table->integer("340_notification_state");
            $table->integer("367_notification_state");
            $table->integer("409_notification_state");
            $table->integer("411_notification_state");
            $table->integer("412_notification_state");
            $table->integer("416_notification_state");
            $table->integer("417_notification_state");
            $table->integer("letter_destination_spare_1");
            $table->integer("letter_destination_spare_2");
            $table->integer("letter_destination_spare_3");
            $table->integer("letter_destination_spare_4");
            $table->integer("letter_destination_spare_5");
            $table->char("spare_3", 8);
            $table->integer("monthly_id")->index();
            $table->timestamps("");
        });
    }

    public function down() {
        if (Schema::connection($this->connect)->hasTable($this->tableName))
        {
            Schema::connection($this->connect)->drop($this->tableName);
        }
    }

}
