<?php

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateCustomerManagementLedgers extends Migration
{

    public $tableName = 'customer_management_ledgers';
    public $connect   = 'mysql_zenon';

    public function up() {
        Schema::connection($this->connect)->create($this->tableName, function(Blueprint $table) {
            $table->increments("id");
            $table->integer("prefecture_code")->index();
            $table->integer("organization_code")->index();
            $table->integer("store_number")->index();
            $table->integer("small_store_number")->index();
            $table->integer("customer_number")->index();
            $table->integer("cir_number")->index();
            $table->integer("lir_number")->index();
            $table->integer("cir_status_01");
            $table->integer("cir_status_02");
            $table->integer("cir_status_03");
            $table->integer("cir_status_04");
            $table->integer("cir_status_05");
            $table->integer("cir_status_06");
            $table->integer("cir_status_07");
            $table->integer("cir_status_08");
            $table->integer("cir_status_09");
            $table->integer("cir_status_10");
            $table->integer("cir_status_11");
            $table->integer("cir_status_12");
            $table->integer("cir_status_13");
            $table->integer("cir_status_14");
            $table->integer("cir_status_15");
            $table->integer("cir_status_16");
            $table->integer("cir_status_17");
            $table->integer("cir_status_18");
            $table->integer("cir_status_19");
            $table->integer("cir_status_20");
            $table->integer("cir_status_21");
            $table->integer("cir_status_22");
            $table->integer("cir_status_23");
            $table->integer("cir_status_24");
            $table->integer("cir_status_25");
            $table->integer("cir_status_26");
            $table->integer("cir_status_27");
            $table->integer("cir_status_28");
            $table->integer("cir_status_29");
            $table->integer("cir_status_30");
            $table->integer("cir_status_31");
            $table->integer("cir_status_32");
            $table->integer("cir_status_33");
            $table->integer("cir_status_34");
            $table->integer("cir_status_35");
            $table->integer("cir_status_36");
            $table->integer("cir_status_37");
            $table->integer("cir_status_38");
            $table->integer("cir_status_39");
            $table->integer("cir_status_40");
            $table->integer("control_store_number")->index();
            $table->integer("customer_fishery_store_number")->index();
            $table->char("kana_name", 30);
            $table->char("kanji_name", 30);
            $table->double("address_code")->index();
            $table->char("kanji_address", 100);
            $table->char("auxiliary_address", 30);
            $table->char("address_state", 1)->index();
            $table->integer("area_code")->index();
            $table->integer("personality_code")->index();
            $table->integer("industry_code")->index();
            $table->integer("staff_code")->index();
            $table->integer("fishery_style")->index();
            $table->date("cir_created_on")->nullable();
            $table->date("birth_on")->nullable();
            $table->integer("jp_year_state")->index();
            $table->integer("jp_year_birthday");
            $table->integer("age");
            $table->integer("gender")->index();
            $table->char("home_phone_number", 14);
            $table->integer("qualification_code")->index();
            $table->date("qualification_acquired_on")->nullable();
            $table->integer("attention_code_1_01");
            $table->integer("attention_code_1_02");
            $table->integer("attention_code_1_03");
            $table->integer("attention_code_1_04");
            $table->integer("attention_code_1_05");
            $table->integer("attention_code_1_06");
            $table->integer("attention_code_1_07");
            $table->integer("attention_code_1_08");
            $table->integer("attention_code_1_09");
            $table->integer("attention_code_1_10");
            $table->integer("attention_code_1_11");
            $table->integer("attention_code_1_12");
            $table->integer("attention_code_1_13");
            $table->integer("attention_code_1_14");
            $table->integer("attention_code_1_15");
            $table->integer("attention_code_1_16");
            $table->integer("jifuri_state_01");
            $table->integer("jifuri_state_02");
            $table->integer("jifuri_state_03");
            $table->integer("jifuri_state_04");
            $table->integer("jifuri_state_05");
            $table->integer("jifuri_state_06");
            $table->integer("jifuri_state_07");
            $table->integer("jifuri_state_08");
            $table->integer("jifuri_state_09");
            $table->integer("jifuri_state_10");
            $table->integer("jifuri_state_11");
            $table->integer("jifuri_state_12");
            $table->integer("jifuri_state_13");
            $table->integer("jifuri_state_14");
            $table->integer("jifuri_state_15");
            $table->integer("jifuri_state_16");
            $table->integer("jifuri_state_17");
            $table->integer("jifuri_state_18");
            $table->integer("jifuri_state_19");
            $table->integer("jifuri_state_20");
            $table->integer("jifuri_state_21");
            $table->char("consolidated_account_state", 1)->index();
            $table->integer("card_issue_state")->index();
            $table->char("is_card_loan_contract_state", 1)->index();
            $table->char("zip_code", 10);
            $table->integer("maruyu_all_amount");
            $table->integer("maruzai_all_count");
            $table->integer("name_correction_level")->index();
            $table->integer("name_collection_number")->index();
            $table->integer("maruyu_store_amount");
            $table->integer("maruzai_store_amount");
            $table->integer("maruyu_usage_amount");
            $table->integer("maruzai_usage_amount");
            $table->integer("interest_rate_state")->index();
            $table->integer("tax_not_application_state")->index();
            $table->date("new_maruyu_managed_on")->nullable();
            $table->integer("new_maruyu_qualification_code")->index();
            $table->char("free_information_state", 4)->index();
            $table->integer("management_control_state")->index();
            $table->char("trade_name", 40);
            $table->char("delegate_name", 40);
            $table->date("taxation_divided_on")->nullable();
            $table->date("maruyu_regard_disuse_on")->nullable();
            $table->date("maruyu_regard_disuse_started_on")->nullable();
            $table->integer("maruyu_usage_balance");
            $table->double("loan_limit_amount");
            $table->char("spare_14", 56);
            $table->integer("loan_attention_code_1_1");
            $table->integer("loan_attention_code_1_2");
            $table->integer("loan_attention_code_1_3");
            $table->integer("loan_attention_code_1_4");
            $table->integer("loan_attention_code_1_5");
            $table->integer("loan_attention_code_1_6");
            $table->integer("loan_attention_code_1_7");
            $table->integer("loan_attention_code_1_8");
            $table->integer("loan_attention_code_1_9");
            $table->integer("loan_attention_code_1_10");
            $table->integer("loan_attention_code_1_11");
            $table->integer("loan_attention_code_1_12");
            $table->integer("loan_attention_code_1_13");
            $table->integer("loan_attention_code_1_14");
            $table->integer("loan_attention_code_1_15");
            $table->integer("loan_attention_code_1_16");
            $table->integer("loan_attention_code_1_17");
            $table->integer("loan_attention_code_1_18");
            $table->integer("loan_attention_code_1_19");
            $table->integer("loan_attention_code_1_20");
            $table->integer("loan_attention_code_1_21");
            $table->integer("loan_attention_code_1_22");
            $table->integer("loan_attention_code_1_23");
            $table->integer("loan_attention_code_1_24");
            $table->integer("loan_attention_code_2_1");
            $table->integer("loan_attention_code_2_2");
            $table->integer("loan_attention_code_2_3");
            $table->integer("loan_attention_code_2_4");
            $table->integer("loan_attention_code_2_5");
            $table->integer("loan_attention_code_2_6");
            $table->integer("loan_attention_code_2_7");
            $table->integer("loan_attention_code_2_8");
            $table->integer("loan_attention_code_2_9");
            $table->integer("loan_attention_code_2_10");
            $table->integer("loan_attention_code_2_11");
            $table->integer("loan_attention_code_2_12");
            $table->integer("loan_attention_code_2_13");
            $table->integer("loan_attention_code_2_14");
            $table->integer("loan_attention_code_2_15");
            $table->integer("loan_attention_code_2_16");
            $table->integer("loan_attention_code_3_1");
            $table->integer("loan_attention_code_3_2");
            $table->integer("loan_attention_code_3_3");
            $table->integer("loan_attention_code_3_4");
            $table->integer("loan_attention_code_3_5");
            $table->integer("loan_attention_code_3_6");
            $table->integer("loan_attention_code_3_7");
            $table->integer("loan_attention_code_3_8");
            $table->integer("loan_attention_code_3_9");
            $table->integer("loan_attention_code_3_10");
            $table->integer("loan_attention_code_3_11");
            $table->integer("loan_attention_code_3_12");
            $table->integer("loan_attention_code_3_13");
            $table->integer("loan_attention_code_3_14");
            $table->integer("loan_attention_code_3_15");
            $table->integer("loan_attention_code_3_16");
            $table->integer("lir_state_001");
            $table->integer("lir_state_002");
            $table->integer("lir_state_003");
            $table->integer("lir_state_004");
            $table->integer("lir_state_005");
            $table->integer("lir_state_006");
            $table->integer("lir_state_007");
            $table->integer("lir_state_008");
            $table->integer("lir_state_009");
            $table->integer("lir_state_010");
            $table->integer("lir_state_011");
            $table->integer("lir_state_012");
            $table->integer("lir_state_013");
            $table->integer("lir_state_014");
            $table->integer("lir_state_015");
            $table->integer("lir_state_016");
            $table->integer("lir_state_017");
            $table->integer("lir_state_018");
            $table->integer("lir_state_019");
            $table->integer("lir_state_020");
            $table->integer("lir_state_021");
            $table->integer("lir_state_022");
            $table->integer("lir_state_023");
            $table->integer("lir_state_024");
            $table->integer("transfer_pay_subject_code")->index();
            $table->double("transfer_pay_account_number")->index();
            $table->integer("transfer_pay_customer_number")->index();
            $table->date("lir_created_on")->nullable();
            $table->date("lir_last_traded_on")->nullable();
            $table->integer("transfer_pay_store_number")->index();
            $table->date("transition_on")->nullable();
            $table->integer("transition_store_number")->index();
            $table->integer("transition_lir_number")->index();
            $table->date("contracted_on")->nullable();
            $table->integer("belong_store_number")->index();
            $table->date("delegate_birth_on")->nullable();
            $table->double("fund");
            $table->integer("employee_count");
            $table->integer("settlement_month");
            $table->integer("loan_management_control_state")->index();
            $table->integer("lir_index_number")->index();
            $table->char("previous_prefecture_code", 1);
            $table->char("spare_1", 52);
            $table->integer("monthly_id")->index();
            $table->timestamps("");
        });
    }

    public function down() {
        if (Schema::connection($this->connect)->hasTable($this->tableName))
        {
            Schema::connection($this->connect)->drop($this->tableName);
        }
    }

}
