<?php

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateJukoCustomerInformationFiles extends Migration
{

    public $tableName = 'juko_customer_files';
    public $connect   = 'mysql_zenon';

    public function up() {
        Schema::connection($this->connect)->create($this->tableName, function(Blueprint $table) {
            $table->increments("id");
            $table->integer("record_code")->index();
            $table->integer("juko_store_code")->index();
            $table->integer("local_juko_store_code")->index();
            $table->integer("bank_code")->index();
            $table->integer("bank_store_code")->index();
            $table->integer("cif_number")->index();
            $table->double("customer_number")->index();
            $table->double("multi_credit_customer_number")->index();
            $table->integer("credit_category_code")->index();
            $table->integer("loan_type_code")->index();
            $table->integer("defrayment_state")->index();
            $table->integer("contract_date");
            $table->integer("increase_amount_repayment_month");
            $table->integer("is_combination_redemption")->index();
            $table->integer("redemption_modify_sign")->index();
            $table->integer("redemption_state")->index();
            $table->date("advance_redemption_asked_term_on")->nullable();
            $table->char("debtor_kana_name", 26);
            $table->char("debtor_kanji_name", 26);
            $table->date("debtor_birth_on")->nullable();
            $table->char("debtor_zip_code", 8);
            $table->char("debtor_kanji_address", 160);
            $table->char("debtor_phone_number", 13);
            $table->char("debtor_workplace_kana_name", 40);
            $table->char("debtor_workplace_phone_number", 13);
            $table->integer("debtor_danshin_join_sign")->index();
            $table->integer("joint_liability_count");
            $table->char("joint_liability_kana_name", 26);
            $table->char("joint_liability_kanji_name", 26);
            $table->date("joint_liability_birth_on")->nullable();
            $table->integer("joint_liability_cohabitation_sign")->index();
            $table->char("joint_liability_zip_code", 8);
            $table->char("joint_liability_kanji_address", 160);
            $table->char("joint_liability_phone_number", 13);
            $table->char("joint_liability_workplace_kana_name", 40);
            $table->char("joint_liability_workplace_phone_number", 13);
            $table->integer("joint_liability_danshin_join_sign");
            $table->integer("security_state")->index();
            $table->double("security_contract_deed_number")->index();
            $table->char("security_kana_name", 26);
            $table->char("security_kanji_name", 26);
            $table->date("security_birth_on")->nullable();
            $table->char("security_zip_code", 8);
            $table->char("security_kanji_address", 160);
            $table->char("security_phone_number", 13);
            $table->char("security_workplace_kana_name", 40);
            $table->char("security_workplace_phone_number", 13);
            $table->double("insuranced_number")->index();
            $table->date("insuranced_term_on")->nullable();
            $table->char("danshin_kana_name", 26);
            $table->char("danshin_kanji_name", 26);
            $table->date("danshin_birth_on")->nullable();
            $table->integer("danshin_join_sign")->index();
            $table->integer("article_house_sign")->index();
            $table->char("article_zip_code", 8);
            $table->char("article_kana_address", 160);
            $table->char("article_kanji_address", 160);
            $table->integer("bank_structure_collateral_state")->index();
            $table->integer("bank_land_collateral_state")->index();
            $table->integer("repayment_end_state")->index();
            $table->date("application_accepted_on")->nullable();
            $table->date("kinsho_contracted_on")->nullable();
            $table->date("last_fund_granted_on")->nullable();
            $table->integer("redemption_bank_store_number")->index();
            $table->integer("redemption_deposit_code")->index();
            $table->integer("redemption_account_number")->index();
            $table->char("redemption_holder", 30);
            $table->integer("special_fee_bank_store_number")->index();
            $table->integer("special_fee_deposit_code")->index();
            $table->integer("special_fee_account_number")->index();
            $table->char("special_fee_holder", 30);
            $table->integer("interest_rate_count");
            $table->date("paid_off_on")->nullable();
            $table->char("bank_note", 20);
            $table->char("note", 80);
            $table->integer("buy_state")->index();
            $table->integer("fee_state")->index();
            $table->float("interest_rate");
            $table->date("last_fee_set_on")->nullable();
            $table->date("first_set_on")->nullable();
            $table->integer("private_danshin_contracted_on");
            $table->char("private_danshin_contract_number", 20)->index();
            $table->integer("payment_state")->index();
            $table->text("spare_1");
            $table->integer("identify_code_01")->index();
            $table->char("credit_number_01", 20)->index();
            $table->integer("interest_supply_state_01")->index();
            $table->integer("step_redemption_state_01")->index();
            $table->integer("interest_rate_application_state_01")->index();
            $table->date("interest_rate_started_on_1_01")->nullable();
            $table->date("last_interest_rate_started_on_01")->nullable();
            $table->date("repayment_ended_on_01")->nullable();
            $table->date("grace_ended_on_01")->nullable();
            $table->date("regular_repaid_on_01")->nullable();
            $table->date("regular_step_ended_on_01")->nullable();
            $table->date("regular_grace_first_repaid_on_01")->nullable();
            $table->date("regular_interest_redeemed_on_01")->nullable();
            $table->date("regular_last_repaid_on_01")->nullable();
            $table->date("bonus_repaid_on_01")->nullable();
            $table->date("bonus_step_ended_on_01")->nullable();
            $table->date("bonus_grace_first_repaid_on_01")->nullable();
            $table->date("bonus_interest_redeemed_on_01")->nullable();
            $table->date("bonus_last_repaid_on_01")->nullable();
            $table->float("interest_rate_1_01");
            $table->float("interest_rate_2_01");
            $table->float("last_interest_rate_01");
            $table->double("regular_allotment_1_01");
            $table->double("regular_allotment_2_01");
            $table->double("regular_allotment_3_01");
            $table->double("regular_allotment_4_01");
            $table->integer("regular_schedule_redemption_count_01");
            $table->integer("regular_redemption_count_01");
            $table->double("bonus_allotment_1_01");
            $table->double("bonus_allotment_2_01");
            $table->double("bonus_allotment_3_01");
            $table->double("bonus_allotment_4_01");
            $table->integer("bonus_schedule_redemption_count_01");
            $table->integer("bonus_redemption_count_01");
            $table->double("regular_loan_amount_01");
            $table->double("regular_loan_balance_01");
            $table->double("regular_uncollected_interest_balance_01");
            $table->double("regular_principal_01");
            $table->double("regular_interest_01");
            $table->double("regular_delayed_damage_01");
            $table->double("regular_redemption_amount_01");
            $table->double("regular_redemption_principal_01");
            $table->double("regular_redemption_interest_01");
            $table->double("regular_next_redemption_amount_01");
            $table->double("regular_next_redemption_principal_01");
            $table->double("regular_next_redemption_interest_01");
            $table->double("bonus_loan_amount_01");
            $table->double("bonus_loan_balance_01");
            $table->double("bonus_uncollected_interest_balance_01");
            $table->double("bonus_principal_01");
            $table->double("bonus_interest_01");
            $table->double("bonus_delayed_damage_01");
            $table->double("bonus_redemption_amount_01");
            $table->double("bonus_redemption_principal_01");
            $table->double("bonus_redemption_interest_01");
            $table->double("bonus_next_redemption_amount_01");
            $table->double("bonus_next_redemption_principal_01");
            $table->double("bonus_next_redemption_interest_01");
            $table->integer("delay_month_count_01");
            $table->double("delay_amount_01");
            $table->integer("advance_delay_month_count_01");
            $table->double("advance_delay_principal_01");
            $table->double("advance_delay_interest_01");
            $table->float("current_interest_rate_01");
            $table->float("next_interest_rate_01");
            $table->date("next_interest_rate_floated_on_01")->nullable();
            $table->double("regular_current_allotment_01");
            $table->date("regular_allotment_changed_on_01")->nullable();
            $table->double("bonus_current_allotment_01");
            $table->date("bonus_allotoment_changed_on_01")->nullable();
            $table->char("spare_2_01", 130);
            $table->integer("identify_code_02")->index();
            $table->char("credit_number_02", 20)->index();
            $table->integer("interest_supply_state_02")->index();
            $table->integer("step_redemption_state_02")->index();
            $table->integer("interest_rate_application_state_02")->index();
            $table->date("interest_rate_started_on_1_02")->nullable();
            $table->date("last_interest_rate_started_on_02")->nullable();
            $table->date("repayment_ended_on_02")->nullable();
            $table->date("grace_ended_on_02")->nullable();
            $table->date("regular_repaid_on_02")->nullable();
            $table->date("regular_step_ended_on_02")->nullable();
            $table->date("regular_grace_first_repaid_on_02")->nullable();
            $table->date("regular_interest_redeemed_on_02")->nullable();
            $table->date("regular_last_repaid_on_02")->nullable();
            $table->date("bonus_repaid_on_02")->nullable();
            $table->date("bonus_step_ended_on_02")->nullable();
            $table->date("bonus_grace_first_repaid_on_02")->nullable();
            $table->date("bonus_interest_redeemed_on_02")->nullable();
            $table->date("bonus_last_repaid_on_02")->nullable();
            $table->float("interest_rate_1_02");
            $table->float("interest_rate_2_02");
            $table->float("last_interest_rate_02");
            $table->double("regular_allotment_1_02");
            $table->double("regular_allotment_2_02");
            $table->double("regular_allotment_3_02");
            $table->double("regular_allotment_4_02");
            $table->integer("regular_schedule_redemption_count_02");
            $table->integer("regular_redemption_count_02");
            $table->double("bonus_allotment_1_02");
            $table->double("bonus_allotment_2_02");
            $table->double("bonus_allotment_3_02");
            $table->double("bonus_allotment_4_02");
            $table->integer("bonus_schedule_redemption_count_02");
            $table->integer("bonus_redemption_count_02");
            $table->double("regular_loan_amount_02");
            $table->double("regular_loan_balance_02");
            $table->double("regular_uncollected_interest_balance_02");
            $table->double("regular_principal_02");
            $table->double("regular_interest_02");
            $table->double("regular_delayed_damage_02");
            $table->double("regular_redemption_amount_02");
            $table->double("regular_redemption_principal_02");
            $table->double("regular_redemption_interest_02");
            $table->double("regular_next_redemption_amount_02");
            $table->double("regular_next_redemption_principal_02");
            $table->double("regular_next_redemption_interest_02");
            $table->double("bonus_loan_amount_02");
            $table->double("bonus_loan_balance_02");
            $table->double("bonus_uncollected_interest_balance_02");
            $table->double("bonus_principal_02");
            $table->double("bonus_interest_02");
            $table->double("bonus_delayed_damage_02");
            $table->double("bonus_redemption_amount_02");
            $table->double("bonus_redemption_principal_02");
            $table->double("bonus_redemption_interest_02");
            $table->double("bonus_next_redemption_amount_02");
            $table->double("bonus_next_redemption_principal_02");
            $table->double("bonus_next_redemption_interest_02");
            $table->integer("delay_month_count_02");
            $table->double("delay_amount_02");
            $table->integer("advance_delay_month_count_02");
            $table->double("advance_delay_principal_02");
            $table->double("advance_delay_interest_02");
            $table->float("current_interest_rate_02");
            $table->float("next_interest_rate_02");
            $table->date("next_interest_rate_floated_on_02")->nullable();
            $table->double("regular_current_allotment_02");
            $table->date("regular_allotment_changed_on_02")->nullable();
            $table->double("bonus_current_allotment_02");
            $table->date("bonus_allotoment_changed_on_02")->nullable();
            $table->char("spare_2_02", 130);
            $table->integer("identify_code_03")->index();
            $table->char("credit_number_03", 20)->index();
            $table->integer("interest_supply_state_03")->index();
            $table->integer("step_redemption_state_03")->index();
            $table->integer("interest_rate_application_state_03")->index();
            $table->date("interest_rate_started_on_1_03")->nullable();
            $table->date("last_interest_rate_started_on_03")->nullable();
            $table->date("repayment_ended_on_03")->nullable();
            $table->date("grace_ended_on_03")->nullable();
            $table->date("regular_repaid_on_03")->nullable();
            $table->date("regular_step_ended_on_03")->nullable();
            $table->date("regular_grace_first_repaid_on_03")->nullable();
            $table->date("regular_interest_redeemed_on_03")->nullable();
            $table->date("regular_last_repaid_on_03")->nullable();
            $table->date("bonus_repaid_on_03")->nullable();
            $table->date("bonus_step_ended_on_03")->nullable();
            $table->date("bonus_grace_first_repaid_on_03")->nullable();
            $table->date("bonus_interest_redeemed_on_03")->nullable();
            $table->date("bonus_last_repaid_on_03")->nullable();
            $table->float("interest_rate_1_03");
            $table->float("interest_rate_2_03");
            $table->float("last_interest_rate_03");
            $table->double("regular_allotment_1_03");
            $table->double("regular_allotment_2_03");
            $table->double("regular_allotment_3_03");
            $table->double("regular_allotment_4_03");
            $table->integer("regular_schedule_redemption_count_03");
            $table->integer("regular_redemption_count_03");
            $table->double("bonus_allotment_1_03");
            $table->double("bonus_allotment_2_03");
            $table->double("bonus_allotment_3_03");
            $table->double("bonus_allotment_4_03");
            $table->integer("bonus_schedule_redemption_count_03");
            $table->integer("bonus_redemption_count_03");
            $table->double("regular_loan_amount_03");
            $table->double("regular_loan_balance_03");
            $table->double("regular_uncollected_interest_balance_03");
            $table->double("regular_principal_03");
            $table->double("regular_interest_03");
            $table->double("regular_delayed_damage_03");
            $table->double("regular_redemption_amount_03");
            $table->double("regular_redemption_principal_03");
            $table->double("regular_redemption_interest_03");
            $table->double("regular_next_redemption_amount_03");
            $table->double("regular_next_redemption_principal_03");
            $table->double("regular_next_redemption_interest_03");
            $table->double("bonus_loan_amount_03");
            $table->double("bonus_loan_balance_03");
            $table->double("bonus_uncollected_interest_balance_03");
            $table->double("bonus_principal_03");
            $table->double("bonus_interest_03");
            $table->double("bonus_delayed_damage_03");
            $table->double("bonus_redemption_amount_03");
            $table->double("bonus_redemption_principal_03");
            $table->double("bonus_redemption_interest_03");
            $table->double("bonus_next_redemption_amount_03");
            $table->double("bonus_next_redemption_principal_03");
            $table->double("bonus_next_redemption_interest_03");
            $table->integer("delay_month_count_03");
            $table->double("delay_amount_03");
            $table->integer("advance_delay_month_count_03");
            $table->double("advance_delay_principal_03");
            $table->double("advance_delay_interest_03");
            $table->float("current_interest_rate_03");
            $table->float("next_interest_rate_03");
            $table->date("next_interest_rate_floated_on_03")->nullable();
            $table->double("regular_current_allotment_03");
            $table->date("regular_allotment_changed_on_03")->nullable();
            $table->double("bonus_current_allotment_03");
            $table->date("bonus_allotoment_changed_on_03")->nullable();
            $table->char("spare_2_03", 130);
            $table->integer("identify_code_04")->index();
            $table->char("credit_number_04", 20)->index();
            $table->integer("interest_supply_state_04")->index();
            $table->integer("step_redemption_state_04")->index();
            $table->integer("interest_rate_application_state_04")->index();
            $table->date("interest_rate_started_on_1_04")->nullable();
            $table->date("last_interest_rate_started_on_04")->nullable();
            $table->date("repayment_ended_on_04")->nullable();
            $table->date("grace_ended_on_04")->nullable();
            $table->date("regular_repaid_on_04")->nullable();
            $table->date("regular_step_ended_on_04")->nullable();
            $table->date("regular_grace_first_repaid_on_04")->nullable();
            $table->date("regular_interest_redeemed_on_04")->nullable();
            $table->date("regular_last_repaid_on_04")->nullable();
            $table->date("bonus_repaid_on_04")->nullable();
            $table->date("bonus_step_ended_on_04")->nullable();
            $table->date("bonus_grace_first_repaid_on_04")->nullable();
            $table->date("bonus_interest_redeemed_on_04")->nullable();
            $table->date("bonus_last_repaid_on_04")->nullable();
            $table->float("interest_rate_1_04");
            $table->float("interest_rate_2_04");
            $table->float("last_interest_rate_04");
            $table->double("regular_allotment_1_04");
            $table->double("regular_allotment_2_04");
            $table->double("regular_allotment_3_04");
            $table->double("regular_allotment_4_04");
            $table->integer("regular_schedule_redemption_count_04");
            $table->integer("regular_redemption_count_04");
            $table->double("bonus_allotment_1_04");
            $table->double("bonus_allotment_2_04");
            $table->double("bonus_allotment_3_04");
            $table->double("bonus_allotment_4_04");
            $table->integer("bonus_schedule_redemption_count_04");
            $table->integer("bonus_redemption_count_04");
            $table->double("regular_loan_amount_04");
            $table->double("regular_loan_balance_04");
            $table->double("regular_uncollected_interest_balance_04");
            $table->double("regular_principal_04");
            $table->double("regular_interest_04");
            $table->double("regular_delayed_damage_04");
            $table->double("regular_redemption_amount_04");
            $table->double("regular_redemption_principal_04");
            $table->double("regular_redemption_interest_04");
            $table->double("regular_next_redemption_amount_04");
            $table->double("regular_next_redemption_principal_04");
            $table->double("regular_next_redemption_interest_04");
            $table->double("bonus_loan_amount_04");
            $table->double("bonus_loan_balance_04");
            $table->double("bonus_uncollected_interest_balance_04");
            $table->double("bonus_principal_04");
            $table->double("bonus_interest_04");
            $table->double("bonus_delayed_damage_04");
            $table->double("bonus_redemption_amount_04");
            $table->double("bonus_redemption_principal_04");
            $table->double("bonus_redemption_interest_04");
            $table->double("bonus_next_redemption_amount_04");
            $table->double("bonus_next_redemption_principal_04");
            $table->double("bonus_next_redemption_interest_04");
            $table->integer("delay_month_count_04");
            $table->double("delay_amount_04");
            $table->integer("advance_delay_month_count_04");
            $table->double("advance_delay_principal_04");
            $table->double("advance_delay_interest_04");
            $table->float("current_interest_rate_04");
            $table->float("next_interest_rate_04");
            $table->date("next_interest_rate_floated_on_04")->nullable();
            $table->double("regular_current_allotment_04");
            $table->date("regular_allotment_changed_on_04")->nullable();
            $table->double("bonus_current_allotment_04");
            $table->date("bonus_allotoment_changed_on_04")->nullable();
            $table->char("spare_2_04", 130);
            $table->text("spare_3");
            $table->integer("monthly_id")->index();
            $table->timestamps("");
        });
    }

    public function down() {
        if (Schema::connection($this->connect)->hasTable($this->tableName))
        {
            Schema::connection($this->connect)->drop($this->tableName);
        }
    }

}
