<?php

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateLoanCustomerInformationFiles extends Migration
{

    /**
     * マイグレーション実行
     *
     * @return void
     */
    public $tableName = 'loan_information_files';
    public $connect   = 'mysql_zenon';

    public function up() {
        Schema::connection($this->connect)->create($this->tableName, function(Blueprint $table) {
            $table->increments("id");
            $table->integer("record_code")->index();
            $table->integer("prefecture_code")->index();
            $table->integer("organization_code")->index();
            $table->integer("store_number")->index();
            $table->integer("lir_number")->index();
            $table->integer("cir_number")->index();
            $table->integer("lir_attention_code_1_001");
            $table->integer("lir_attention_code_1_002");
            $table->integer("lir_attention_code_1_003");
            $table->integer("lir_attention_code_1_004");
            $table->integer("lir_attention_code_1_005");
            $table->integer("lir_attention_code_1_006");
            $table->integer("lir_attention_code_1_007");
            $table->integer("lir_attention_code_1_008");
            $table->integer("lir_attention_code_1_009");
            $table->integer("lir_attention_code_1_010");
            $table->integer("lir_attention_code_1_011");
            $table->integer("lir_attention_code_1_012");
            $table->integer("lir_attention_code_1_013");
            $table->integer("lir_attention_code_1_014");
            $table->integer("lir_attention_code_1_015");
            $table->integer("lir_attention_code_1_016");
            $table->integer("lir_attention_code_1_017");
            $table->integer("lir_attention_code_1_018");
            $table->integer("lir_attention_code_1_019");
            $table->integer("lir_attention_code_1_020");
            $table->integer("lir_attention_code_1_021");
            $table->integer("lir_attention_code_1_022");
            $table->integer("lir_attention_code_1_023");
            $table->integer("lir_attention_code_1_024");
            $table->integer("lir_attention_code_2_001");
            $table->integer("lir_attention_code_2_002");
            $table->integer("lir_attention_code_2_003");
            $table->integer("lir_attention_code_2_004");
            $table->integer("lir_attention_code_2_005");
            $table->integer("lir_attention_code_2_006");
            $table->integer("lir_attention_code_2_007");
            $table->integer("lir_attention_code_2_008");
            $table->integer("lir_attention_code_2_009");
            $table->integer("lir_attention_code_2_010");
            $table->integer("lir_attention_code_2_011");
            $table->integer("lir_attention_code_2_012");
            $table->integer("lir_attention_code_2_013");
            $table->integer("lir_attention_code_2_014");
            $table->integer("lir_attention_code_2_015");
            $table->integer("lir_attention_code_2_016");
            $table->integer("lir_attention_code_3_001");
            $table->integer("lir_attention_code_3_002");
            $table->integer("lir_attention_code_3_003");
            $table->integer("lir_attention_code_3_004");
            $table->integer("lir_attention_code_3_005");
            $table->integer("lir_attention_code_3_006");
            $table->integer("lir_attention_code_3_007");
            $table->integer("lir_attention_code_3_008");
            $table->integer("lir_attention_code_3_009");
            $table->integer("lir_attention_code_3_010");
            $table->integer("lir_attention_code_3_011");
            $table->integer("lir_attention_code_3_012");
            $table->integer("lir_attention_code_3_013");
            $table->integer("lir_attention_code_3_014");
            $table->integer("lir_attention_code_3_015");
            $table->integer("lir_attention_code_3_016");
            $table->integer("lir_state_001");
            $table->integer("lir_state_002");
            $table->integer("lir_state_003");
            $table->integer("lir_state_004");
            $table->integer("lir_state_005");
            $table->integer("lir_state_006");
            $table->integer("lir_state_007");
            $table->integer("lir_state_008");
            $table->integer("lir_state_009");
            $table->integer("lir_state_010");
            $table->integer("lir_state_011");
            $table->integer("lir_state_012");
            $table->integer("lir_state_013");
            $table->integer("lir_state_014");
            $table->integer("lir_state_015");
            $table->integer("lir_state_016");
            $table->integer("lir_state_017");
            $table->integer("lir_state_018");
            $table->integer("lir_state_019");
            $table->integer("lir_state_020");
            $table->integer("lir_state_021");
            $table->integer("lir_state_022");
            $table->integer("lir_state_023");
            $table->integer("lir_state_024");
            $table->char("serial_account_number_001", 1);
            $table->char("serial_account_number_002", 1);
            $table->char("serial_account_number_003", 1);
            $table->char("serial_account_number_004", 1);
            $table->char("serial_account_number_005", 1);
            $table->char("serial_account_number_006", 1);
            $table->char("serial_account_number_007", 1);
            $table->char("serial_account_number_008", 1);
            $table->char("serial_account_number_009", 1);
            $table->char("serial_account_number_010", 1);
            $table->char("serial_account_number_011", 1);
            $table->char("serial_account_number_012", 1);
            $table->char("serial_account_number_013", 1);
            $table->char("serial_account_number_014", 1);
            $table->char("serial_account_number_015", 1);
            $table->char("serial_account_number_016", 1);
            $table->char("serial_account_number_017", 1);
            $table->char("serial_account_number_018", 1);
            $table->char("serial_account_number_019", 1);
            $table->char("serial_account_number_020", 1);
            $table->char("serial_account_number_021", 1);
            $table->char("serial_account_number_022", 1);
            $table->char("serial_account_number_023", 1);
            $table->char("serial_account_number_024", 1);
            $table->char("serial_account_number_025", 1);
            $table->char("serial_account_number_026", 1);
            $table->char("serial_account_number_027", 1);
            $table->char("serial_account_number_028", 1);
            $table->char("serial_account_number_029", 1);
            $table->char("serial_account_number_030", 1);
            $table->char("serial_account_number_031", 1);
            $table->char("serial_account_number_032", 1);
            $table->char("serial_account_number_033", 1);
            $table->char("serial_account_number_034", 1);
            $table->char("serial_account_number_035", 1);
            $table->char("serial_account_number_036", 1);
            $table->char("serial_account_number_037", 1);
            $table->char("serial_account_number_038", 1);
            $table->char("serial_account_number_039", 1);
            $table->char("serial_account_number_040", 1);
            $table->char("serial_account_number_041", 1);
            $table->char("serial_account_number_042", 1);
            $table->char("serial_account_number_043", 1);
            $table->char("serial_account_number_044", 1);
            $table->char("serial_account_number_045", 1);
            $table->char("serial_account_number_046", 1);
            $table->char("serial_account_number_047", 1);
            $table->char("serial_account_number_048", 1);
            $table->char("serial_account_number_049", 1);
            $table->char("serial_account_number_050", 1);
            $table->char("serial_account_number_051", 1);
            $table->char("serial_account_number_052", 1);
            $table->char("serial_account_number_053", 1);
            $table->char("serial_account_number_054", 1);
            $table->char("serial_account_number_055", 1);
            $table->char("serial_account_number_056", 1);
            $table->char("serial_account_number_057", 1);
            $table->char("serial_account_number_058", 1);
            $table->char("serial_account_number_059", 1);
            $table->char("serial_account_number_060", 1);
            $table->char("serial_account_number_061", 1);
            $table->char("serial_account_number_062", 1);
            $table->char("serial_account_number_063", 1);
            $table->char("serial_account_number_064", 1);
            $table->char("serial_account_number_065", 1);
            $table->char("serial_account_number_066", 1);
            $table->char("serial_account_number_067", 1);
            $table->char("serial_account_number_068", 1);
            $table->char("serial_account_number_069", 1);
            $table->char("serial_account_number_070", 1);
            $table->char("serial_account_number_071", 1);
            $table->char("serial_account_number_072", 1);
            $table->char("serial_account_number_073", 1);
            $table->char("serial_account_number_074", 1);
            $table->char("serial_account_number_075", 1);
            $table->char("serial_account_number_076", 1);
            $table->char("serial_account_number_077", 1);
            $table->char("serial_account_number_078", 1);
            $table->char("serial_account_number_079", 1);
            $table->char("serial_account_number_080", 1);
            $table->char("serial_account_number_081", 1);
            $table->char("serial_account_number_082", 1);
            $table->char("serial_account_number_083", 1);
            $table->char("serial_account_number_084", 1);
            $table->char("serial_account_number_085", 1);
            $table->char("serial_account_number_086", 1);
            $table->char("serial_account_number_087", 1);
            $table->char("serial_account_number_088", 1);
            $table->char("serial_account_number_089", 1);
            $table->char("serial_account_number_090", 1);
            $table->char("serial_account_number_091", 1);
            $table->char("serial_account_number_092", 1);
            $table->char("serial_account_number_093", 1);
            $table->char("serial_account_number_094", 1);
            $table->char("serial_account_number_095", 1);
            $table->char("serial_account_number_096", 1);
            $table->char("serial_account_number_097", 1);
            $table->char("serial_account_number_098", 1);
            $table->char("serial_account_number_099", 1);
            $table->char("serial_account_number_100", 1);
            $table->char("serial_account_number_101", 1);
            $table->char("serial_account_number_102", 1);
            $table->char("serial_account_number_103", 1);
            $table->char("serial_account_number_104", 1);
            $table->integer("last_register_position");
            $table->integer("extreme_number_serial");
            $table->integer("active_account_count");
            $table->integer("extreme_set_count");
            $table->double("extreme_set_amount");
            $table->integer("limit_set_count");
            $table->double("limit_set_amount");
            $table->integer("collateral_set_count");
            $table->integer("payment_information_key")->index();
            $table->integer("transfer_payment_subject_code")->index();
            $table->double("transfer_payment_account_number")->index();
            $table->integer("transfer_payment_customer_number")->index();
            $table->date("lir_created_on")->nullable();
            $table->integer("fir_number")->index();
            $table->date("lir_last_traded_on")->nullable();
            $table->integer("conservation_number_serial");
            $table->integer("transfer_payment_store_number")->index();
            $table->integer("application_account_count");
            $table->integer("application_extreme_count");
            $table->date("transition_on")->nullable();
            $table->integer("transition_store_number")->index();
            $table->integer("transition_lir_number")->index();
            $table->date("trade_stopped_on")->nullable();
            $table->integer("fishery_style")->index();
            $table->date("contracted_on")->nullable();
            $table->integer("belong_store_number")->index();
            $table->date("delegate_birth_on")->nullable();
            $table->double("fund");
            $table->integer("employee_count");
            $table->char("business_state", 20);
            $table->integer("main_state")->index();
            $table->integer("settlement_month")->index();
            $table->integer("credit_valuation_state")->index();
            $table->integer("loan_policy_state")->index();
            $table->integer("limitation_collateral_count");
            $table->double("limitation_collateral_amount");
            $table->integer("revolving_collateral_count");
            $table->double("revolving_collateral_amount");
            $table->integer("shogashi_execution_count");
            $table->double("shogashi_execution_balance");
            $table->integer("shogashi_delay_count");
            $table->integer("loan_execution_count");
            $table->double("loan_execution_balance");
            $table->integer("loan_delay_count");
            $table->integer("tegashi_execution_count");
            $table->double("tegashi_execution_balance");
            $table->integer("tegashi_delay_count");
            $table->integer("yotan_execution_count");
            $table->double("yotan_execution_balance");
            $table->integer("yotan_delay_count");
            $table->integer("tsumitan_execution_count");
            $table->double("tsumitan_execution_balance");
            $table->integer("tsumitan_delay_count");
            $table->integer("shotan_tegashi_execution_count");
            $table->double("shotan_tegashi_execution_balance");
            $table->integer("shotan_tegashi_delay_count");
            $table->integer("shote_execution_count");
            $table->double("shote_execution_balance");
            $table->integer("shote_delay_count");
            $table->integer("dairigashi_execution_count");
            $table->double("dairigashi_execution_balance");
            $table->integer("dairigashi_delay_count");
            $table->integer("juko_execution_count");
            $table->double("juko_execution_balance");
            $table->integer("juko_delay_count");
            $table->integer("junen_execution_count");
            $table->double("junen_execution_balance");
            $table->integer("junen_delay_count");
            $table->integer("noko_execution_count");
            $table->double("noko_execution_balance");
            $table->integer("noko_delay_count");
            $table->integer("pension_execution_count");
            $table->double("pension_execution_balance");
            $table->integer("pension_delay_count");
            $table->integer("kokko_execution_count");
            $table->double("kokko_execution_balance");
            $table->integer("kokko_delay_count");
            $table->integer("jotogai_execution_count");
            $table->double("jotogai_execution_balance");
            $table->integer("jotogai_delay_count");
            $table->integer("welfare_execution_count");
            $table->double("welfare_execution_balance");
            $table->integer("welfare_delay_count");
            $table->integer("improvement_fund_execution_count");
            $table->double("improvement_fund_execution_balance");
            $table->integer("improvement_fund_delay_count");
            $table->integer("fixed_credit_execution_count");
            $table->double("fixed_credit_execution_balance");
            $table->integer("fixed_credit_delay_count");
            $table->integer("payment_agreement_execution_count");
            $table->double("payment_agreement_execution_balance");
            $table->integer("overdraft_execution_count");
            $table->double("overdraft_execution_balance");
            $table->integer("ryuho_amount_count");
            $table->double("ryuho_amount_balance");
            $table->integer("ukeire_amount_count");
            $table->double("ukeire_amount_balance");
            $table->double("institution_fund_balance");
            $table->integer("payment_agreement_delay_count");
            $table->integer("uncollected_discount_fee_count");
            $table->date("settlement_1_on")->nullable();
            $table->integer("profit_and_loss_state_1")->index();
            $table->double("after_tax_profit_loss_amount_1");
            $table->double("yearly_turnover_1");
            $table->double("depreciation_amount_1");
            $table->double("ordinary_profit_1");
            $table->date("settlement_2_on")->nullable();
            $table->integer("profit_and_loss_state_2")->index();
            $table->double("after_tax_profit_loss_amount_2");
            $table->double("yearly_turnover_2");
            $table->double("depreciation_amount_2");
            $table->double("ordinary_profit_2");
            $table->integer("package_payment_detail_count");
            $table->double("package_payment_detail_balance");
            $table->date("union_on")->nullable();
            $table->integer("lir_index_number")->index();
            $table->integer("credit_information_state")->index();
            $table->integer("industry_state")->index();
            $table->char("spare_1", 63);
            $table->integer("customer_number")->index();
            $table->integer("cir_state_001");
            $table->integer("cir_state_002");
            $table->integer("cir_state_003");
            $table->integer("cir_state_004");
            $table->integer("cir_state_005");
            $table->integer("cir_state_006");
            $table->integer("cir_state_007");
            $table->integer("cir_state_008");
            $table->integer("cir_state_009");
            $table->integer("cir_state_010");
            $table->integer("cir_state_011");
            $table->integer("cir_state_012");
            $table->integer("cir_state_013");
            $table->integer("cir_state_014");
            $table->integer("cir_state_015");
            $table->integer("cir_state_016");
            $table->integer("cir_state_017");
            $table->integer("cir_state_018");
            $table->integer("cir_state_019");
            $table->integer("cir_state_020");
            $table->integer("cir_state_021");
            $table->integer("cir_state_022");
            $table->integer("cir_state_023");
            $table->integer("cir_state_024");
            $table->integer("cir_state_025");
            $table->integer("cir_state_026");
            $table->integer("cir_state_027");
            $table->integer("cir_state_028");
            $table->integer("cir_state_029");
            $table->integer("cir_state_030");
            $table->integer("cir_state_031");
            $table->integer("cir_state_032");
            $table->integer("cir_state_033");
            $table->integer("cir_state_034");
            $table->integer("cir_state_035");
            $table->integer("cir_state_036");
            $table->integer("cir_state_037");
            $table->integer("cir_state_038");
            $table->integer("cir_state_039");
            $table->integer("cir_state_040");
            $table->date("cir_created_on")->nullable();
            $table->integer("cir_attention_code_1_001");
            $table->integer("cir_attention_code_1_002");
            $table->integer("cir_attention_code_1_003");
            $table->integer("cir_attention_code_1_004");
            $table->integer("cir_attention_code_1_005");
            $table->integer("cir_attention_code_1_006");
            $table->integer("cir_attention_code_1_007");
            $table->integer("cir_attention_code_1_008");
            $table->integer("cir_attention_code_3_001");
            $table->integer("cir_attention_code_3_002");
            $table->integer("cir_attention_code_3_003");
            $table->integer("cir_attention_code_3_004");
            $table->integer("cir_attention_code_3_005");
            $table->integer("cir_attention_code_3_006");
            $table->integer("cir_attention_code_3_007");
            $table->integer("cir_attention_code_3_008");
            $table->integer("total_account_count");
            $table->char("name_initial", 1)->index();
            $table->char("kana_name", 44);
            $table->char("kanji_name", 44);
            $table->char("address_state", 1)->index();
            $table->double("address_code")->index();
            $table->char("spare_2", 3);
            $table->char("zip_code", 7)->index();
            $table->char("kanji_address", 100);
            $table->char("auxiliary_address", 30);
            $table->integer("gender")->index();
            $table->date("birth_on")->nullable();
            $table->char("home_phone_number", 14);
            $table->integer("qualification_code")->index();
            $table->date("qualification_got_on")->nullable();
            $table->integer("personality_code")->index();
            $table->integer("auxiliary_code")->index();
            $table->integer("area_code")->index();
            $table->integer("industry_code")->index();
            $table->integer("staff_code")->index();
            $table->char("jifuri_state_001", 1);
            $table->char("jifuri_state_002", 1);
            $table->char("jifuri_state_003", 1);
            $table->char("jifuri_state_004", 1);
            $table->char("jifuri_state_005", 1);
            $table->char("jifuri_state_006", 1);
            $table->char("jifuri_state_007", 1);
            $table->char("jifuri_state_008", 1);
            $table->char("jifuri_state_009", 1);
            $table->char("jifuri_state_010", 1);
            $table->char("jifuri_state_011", 1);
            $table->char("jifuri_state_012", 1);
            $table->char("jifuri_state_013", 1);
            $table->char("jifuri_state_014", 1);
            $table->char("jifuri_state_015", 1);
            $table->char("jifuri_state_016", 1);
            $table->char("jifuri_state_017", 1);
            $table->char("jifuri_state_022", 1);
            $table->char("jifuri_state_023", 1);
            $table->char("jifuri_state_024", 1);
            $table->char("jifuri_state_025", 1);
            $table->char("jifuri_state_026", 1);
            $table->char("jifuri_state_027", 1);
            $table->char("jifuri_state_028", 1);
            $table->char("jifuri_state_029", 1);
            $table->char("jifuri_state_030", 1);
            $table->char("jifuri_state_031", 1);
            $table->char("jifuri_state_032", 1);
            $table->char("jifuri_state_033", 1);
            $table->char("jifuri_state_034", 1);
            $table->char("jifuri_state_035", 1);
            $table->char("jifuri_state_036", 1);
            $table->integer("conversion_state");
            $table->integer("small_store_number")->index();
            $table->char("previous_prefecture_code", 1);
            $table->char("spare_3", 110);
            $table->integer("monthly_id")->index();
            $table->timestamps("");
        });
    }

    public function down() {
        if (Schema::connection($this->connect)->hasTable($this->tableName))
        {
            Schema::connection($this->connect)->drop($this->tableName);
        }
    }

}
